var editResponseCol = 74;                                             // Col# in which you want to save the link to the editable event creation form
var eventCreatorIndex = 1;
var sessionTitleIndex = 2;
var publishIndex = 5;
var maxParticipantsIndex = 6;
var fac1Index = 7;
var fac1EmailIndex = 8;
var fac2Index = 9;
var fac2EmailIndex = 10;
var fac3Index = 11;
var fac3EmailIndex = 12;
var divisionIndex = 15;
var sessionStartTimeIndex = 17;
var sessionEndTimeIndex = 18;
var sessionFirstDateIndex = 21;
var sessionLastDateIndex = 31;
var ctleIndex = 32;
var fbScheduleIndex = 45;
var sessionDescriptionIndex = 3;
var sessionLocationIndex = 19;
var sessionDatesIndex = 69;
var sessionFacsIndex = 70;
var sessionTimesIndex = 71;
var idCol = 51;
var directorEmailCol = 57;
var regUrlCol = 53;
var timesCol = 72;
var fullPlTitleCol = 52;
var firstFullDateCol = 59;
var allFacsCol = 71;
var regFlyerCol = 76;
var regFlyerIdCol = 78;
var regFlyerEditDateCol = 77;
var lastDateOfEventCol = 81;
var timeDurationCol = 54;
var closedRegUrlCol = 58;
var fbFormStatusCol = 82;
var signInSheetCol = 83;
var daysInEventCol = 85;
var attendanceTrackRateCol = 87;
var archiveCol = 88;
var facReminderCol = 89;
var attendanceFolderCol = 91;
var calEventCol = 92;
var otherInfoIndex = 35;
var notifyRegistrantsIndex = 42;
var emailRemindSentCol = 50;
var responseIdIndex = 74;
var archivedIndex = 87;
var signInCodeCol = 90;
var emailConfCol = 93;
var waitlistCol = 44;
var waitlistNum = 45;

var fb_sessionTitleIndex = 1;
var fb_sessionNum = 2;

//these refer to the question indexes in the event creation form
var cf_sessionTitleIndex = 0;
var cf_descriptionIndex = 1;
var cf_locationIndex = 17;
var cf_firstDateIndex = 19;
var cf_lastDateIndex = 29;
var cf_firstFacNameIndex = 5;
var cf_lastFacNameIndex = 9;
var cf_startTimeIndex = 15;
var cf_endTimeIndex = 16;
var cf_eventIdIndex = 11; //1.12

//these refer to column indexes in the event registration spreadsheet
var r_eventTitleIndex = 1;
var r_firstNameIndex = 2;
var r_lastNameIndex = 3;
var r_emailindex = 4;
var r_eventIdIndex = 18;
var r_fbFormIndex = 56;
var r_fbFormStatsIndex = 57;
var r_waitlistIndex = 63;
